/** BIST 30 constituents + benchmark index (Yahoo Finance .IS suffix). */
const BIST_30 = [
  "ALTINS1.IS",
  "THYAO.IS",
  "GARAN.IS",
  "AKBNK.IS",
  "ISCTR.IS",
  "YKBNK.IS",
  "SAHOL.IS",
  "KCHOL.IS",
  "EREGL.IS",
  "TUPRS.IS",
  "BIMAS.IS",
  "SISE.IS",
  "ASELS.IS",
  "SASA.IS",
  "PGSUS.IS",
  "TCELL.IS",
  "FROTO.IS",
  "TOASO.IS",
  "MGROS.IS",
  "ARCLK.IS",
  "HALKB.IS",
  "VAKBN.IS",
  "PETKM.IS",
  "KOZAL.IS",
  "TAVHL.IS",
  "ENKAI.IS",
  "TTKOM.IS",
  "DOHOL.IS",
  "SOKM.IS",
  "EKGYO.IS",
  "KRDMD.IS",
];

const BENCHMARK = "XU100.IS";

const DISPLAY_NAMES = {
  "ALTINS1.IS": "Darphane Altın Sertifikası",
  "THYAO.IS": "Türk Hava Yolları",
  "GARAN.IS": "Garanti BBVA",
  "AKBNK.IS": "Akbank",
  "ISCTR.IS": "İş Bankası",
  "YKBNK.IS": "Yapı Kredi",
  "SAHOL.IS": "Sabancı Holding",
  "KCHOL.IS": "Koç Holding",
  "EREGL.IS": "Ereğli Demir Çelik",
  "TUPRS.IS": "Tüpraş",
  "BIMAS.IS": "BIM",
  "SISE.IS": "Şişecam",
  "ASELS.IS": "Aselsan",
  "SASA.IS": "SASA Polyester",
  "PGSUS.IS": "Pegasus",
  "TCELL.IS": "Turkcell",
  "FROTO.IS": "Ford Otosan",
  "TOASO.IS": "Tofaş",
  "MGROS.IS": "Migros",
  "ARCLK.IS": "Arçelik",
  "HALKB.IS": "Halkbank",
  "VAKBN.IS": "VakıfBank",
  "PETKM.IS": "Petkim",
  "KOZAL.IS": "Koza Altın",
  "TAVHL.IS": "TAV Havalimanları",
  "ENKAI.IS": "Enka İnşaat",
  "TTKOM.IS": "Türk Telekom",
  "DOHOL.IS": "Doğan Holding",
  "SOKM.IS": "Şok Marketler",
  "EKGYO.IS": "Emlak Konut GYO",
  "KRDMD.IS": "Kardemir",
  "XU100.IS": "BIST 100",
};

module.exports = { BIST_30, BENCHMARK, DISPLAY_NAMES };
